// This file is automatically generated by `npm run db:types`. Do not edit it directly.
//
// Placeholder until the database schema is generated. It mirrors the exact shape
// the Supabase CLI emits for an empty `public` schema, so regenerating will
// simply overwrite this with the same structure (no consumer changes needed).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: { [_ in never]: never };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
