// RCLIP — Opportunity Workspace · dummy JSON (frontend shell only).
// Represents one realistic multi-product Investment Banking opportunity.
import type { Opportunity } from "./types";

export const mockOpportunity: Opportunity = {
  code: "RC-OPP-000418",
  title: "Skyline Infra — Construction Finance + Working Capital",
  type: "Construction Finance",
  status: "open",
  health: "watch",
  healthScore: 68,
  priority: "high",
  engagementModel: "Exclusive Mandate",
  objective: "Project Funding",
  acquisitionChannel: "Builder Referral",
  introducedBy: "Mehta & Associates",
  expectedCloseDate: "2026-08-14",
  overallReadiness: 62,
  confidentiality: "restricted",
  tags: ["Priority Deal", "Repeat Client", "Multi-Product"],
  client: {
    kind: "entity",
    name: "Skyline Infra Developers Pvt Ltd",
    classification: "Strategic",
    strength: "Excellent",
    industry: "Real Estate — Construction",
    city: "Pune",
    totalBusinessValue: 184000000,
    lastInteraction: "2026-07-01",
  },
  stages: [
    { code: "lead", name: "Lead", state: "done" },
    { code: "qualification", name: "Qualification", state: "done" },
    { code: "financial_analysis", name: "Financial Analysis", state: "done" },
    { code: "presentation_ready", name: "Presentation Ready", state: "current" },
    { code: "institution_match", name: "Institution Matching", state: "upcoming" },
    { code: "proposal_sent", name: "Proposal Sent", state: "upcoming" },
    { code: "credit_review", name: "Credit Review", state: "upcoming" },
    { code: "sanction", name: "Sanction", state: "upcoming" },
    { code: "documentation", name: "Documentation", state: "upcoming" },
    { code: "disbursement", name: "Disbursement", state: "upcoming" },
  ],
  coverageTeam: [
    { id: "t1", name: "A. Kulkarni", initials: "AK", teamRole: "Primary Investment Banker", isPrimary: true },
    { id: "t2", name: "R. Nair", initials: "RN", teamRole: "Supporting Investment Banker" },
    { id: "t3", name: "S. Iyer", initials: "SI", teamRole: "Credit Coordinator" },
    { id: "t4", name: "P. Desai", initials: "PD", teamRole: "Operations Executive" },
    { id: "t5", name: "M. Rao", initials: "MR", teamRole: "Documentation Executive" },
  ],
  products: [
    { id: "p1", name: "Construction Finance", type: "construction_finance", requestedAmount: 450000000, tenureMonths: 48, isPrimary: true, subStatus: "active" },
    { id: "p2", name: "Working Capital", type: "working_capital", requestedAmount: 75000000, tenureMonths: 12, subStatus: "active" },
    { id: "p3", name: "Lease Rental Discounting", type: "lease_rental_discounting", requestedAmount: 120000000, tenureMonths: 96, subStatus: "active" },
  ],
  participants: [
    { id: "pa1", kind: "entity", name: "Skyline Infra Developers Pvt Ltd", role: "Client", isPrimaryClient: true },
    { id: "pa2", kind: "entity", name: "Skyline Infra Developers Pvt Ltd", role: "Borrower" },
    { id: "pa3", kind: "contact", name: "Rohan K█████", role: "Director" },
    { id: "pa4", kind: "contact", name: "Neha S█████", role: "Promoter" },
    { id: "pa5", kind: "contact", name: "V. J█████", role: "Guarantor" },
    { id: "pa6", kind: "contact", name: "CA Anil M█████", role: "Chartered Accountant" },
    { id: "pa7", kind: "contact", name: "Adv. Priya R█████", role: "Advocate" },
    { id: "pa8", kind: "contact", name: "S. B█████", role: "Valuer" },
  ],
  institutionTracks: [
    { id: "it1", institution: "HDFC Bank", product: "Construction Finance", status: "credit_discussion", matchScore: 92, sanctionedAmount: undefined, roi: 9.25, selected: true },
    { id: "it2", institution: "ICICI Bank", product: "Construction Finance", status: "documents_pending", matchScore: 88, roi: 9.4 },
    { id: "it3", institution: "Bajaj Housing Finance", product: "Lease Rental Discounting", status: "application_sent", matchScore: 84, roi: 9.75 },
    { id: "it4", institution: "Kotak Mahindra Bank", product: "Working Capital", status: "shortlisted", matchScore: 79 },
    { id: "it5", institution: "Axis Bank", product: "Construction Finance", status: "rejected", matchScore: 61 },
  ],
  readiness: [
    { code: "client_information", name: "Client Information", score: 100, passThreshold: 100, gating: true },
    { code: "financial_information", name: "Financial Information", score: 85, passThreshold: 100, gating: true },
    { code: "documents", name: "Documents", score: 64, passThreshold: 80, gating: true },
    { code: "collateral", name: "Collateral", score: 70, passThreshold: 60, gating: false },
    { code: "compliance", name: "Compliance", score: 90, passThreshold: 100, gating: true },
    { code: "credit", name: "Credit", score: 55, passThreshold: 60, gating: false },
    { code: "legal", name: "Legal", score: 40, passThreshold: 60, gating: false },
    { code: "technical", name: "Technical", score: 75, passThreshold: 60, gating: false },
    { code: "communication", name: "Communication", score: 80, passThreshold: 50, gating: false },
  ],
  tasks: [
    { id: "tk1", title: "Collect audited financials FY24-25", origin: "missing_documents", status: "in_progress", assignee: "S. Iyer", dueDate: "2026-07-05" },
    { id: "tk2", title: "Respond to HDFC credit queries", origin: "institution_reply", status: "open", assignee: "A. Kulkarni", dueDate: "2026-07-04" },
    { id: "tk3", title: "Prepare project valuation summary", origin: "workflow", status: "open", assignee: "M. Rao", dueDate: "2026-07-08" },
    { id: "tk4", title: "Review title search report", origin: "manual", status: "open", assignee: "Adv. Priya R.", dueDate: "2026-07-10" },
    { id: "tk5", title: "Draft information sheet", origin: "ai", status: "open", assignee: "A. Kulkarni" },
    { id: "tk6", title: "KYC verification of directors", origin: "workflow", status: "done", assignee: "P. Desai" },
  ],
  timeline: [
    { id: "e1", eventType: "Institution Replied", source: "institution", actor: "HDFC Bank", summary: "HDFC raised 3 credit queries on the CF proposal", occurredAt: "2026-07-02T14:20:00" },
    { id: "e2", eventType: "Document Uploaded", source: "manual", actor: "S. Iyer", summary: "Uploaded provisional financials FY24-25", occurredAt: "2026-07-02T11:05:00" },
    { id: "e3", eventType: "Readiness Updated", source: "system", actor: "System", summary: "Documents readiness moved 58% → 64%", occurredAt: "2026-07-02T11:06:00" },
    { id: "e4", eventType: "Email Sent", source: "manual", actor: "A. Kulkarni", summary: "Sent proposal teaser to ICICI Bank", occurredAt: "2026-07-01T17:40:00" },
    { id: "e5", eventType: "Coverage Team Changed", source: "manual", actor: "Branch Admin", summary: "Added M. Rao as Documentation Executive", occurredAt: "2026-07-01T09:15:00" },
    { id: "e6", eventType: "Opportunity Created", source: "system", actor: "A. Kulkarni", summary: "Opportunity RC-OPP-000418 created", occurredAt: "2026-06-28T10:00:00" },
  ],
  communications: [
    { id: "c1", channel: "institution_reply", direction: "inbound", party: "HDFC Bank", subject: "Re: Skyline CF — credit queries", preview: "We need clarity on the escrow mechanism and the...", occurredAt: "2026-07-02T14:20:00" },
    { id: "c2", channel: "email", direction: "outbound", party: "ICICI Bank", subject: "Skyline Infra — Construction Finance proposal", preview: "Please find the indicative proposal for a ₹45 Cr...", occurredAt: "2026-07-01T17:40:00" },
    { id: "c3", channel: "meeting", direction: "internal", party: "Coverage Team", subject: "Deal review — presentation readiness", preview: "Aligned on institution shortlist and pending docs...", occurredAt: "2026-07-01T12:00:00" },
    { id: "c4", channel: "phone_call", direction: "outbound", party: "Rohan K█████", subject: "Financials follow-up", preview: "Requested audited statements and GST returns...", occurredAt: "2026-06-30T16:30:00" },
  ],
  documents: [
    { id: "d1", name: "PAN — Company", category: "kyc", status: "verified", mandatory: true },
    { id: "d2", name: "Certificate of Incorporation", category: "kyc", status: "verified", mandatory: true },
    { id: "d3", name: "Audited Financials FY24-25", category: "income", status: "pending", mandatory: true },
    { id: "d4", name: "GST Returns (12 months)", category: "banking", status: "received", mandatory: true },
    { id: "d5", name: "Project Report", category: "business", status: "received", mandatory: true },
    { id: "d6", name: "Title Search Report", category: "legal", status: "pending", mandatory: true },
    { id: "d7", name: "Valuation Report", category: "technical", status: "received", mandatory: false },
    { id: "d8", name: "Sanction Plan Approval", category: "property", status: "pending", mandatory: true },
  ],
  financials: {
    pipelineValue: 645000000,
    expectedRevenue: 9675000,
    actualRevenue: 0,
    institutionReceivable: 0,
    payables: 0,
    profitability: 0,
    currency: "INR",
  },
  ai: [
    { id: "ai1", kind: "summary", title: "Executive Summary", body: "Strategic repeat client seeking ₹64.5 Cr across construction finance, working capital and LRD. Strong sponsor profile; HDFC leading credit discussion at 9.25%." },
    { id: "ai2", kind: "missing", title: "Missing Information", body: "Audited FY24-25 financials and title search report are blocking the Documents and Legal readiness gates." },
    { id: "ai3", kind: "recommendation", title: "Institution Recommendation", body: "HDFC (92) and ICICI (88) are the strongest matches for CF; consider Bajaj HFC for LRD tranche." },
    { id: "ai4", kind: "risk", title: "Credit Risk Summary", body: "Moderate: project-stage exposure offset by collateral cover and sponsor track record." },
    { id: "ai5", kind: "follow_up", title: "Follow-up Suggestions", body: "Respond to HDFC queries within SLA (due tomorrow) and chase audited financials to unblock readiness." },
  ],
  watchers: [
    { id: "w1", name: "Managing Partner", initials: "MP" },
    { id: "w2", name: "Head of Credit", initials: "HC" },
  ],
  createdAt: "2026-06-28T10:00:00",
  updatedAt: "2026-07-02T14:20:00",
  version: 14,
};
